**Table of contents**<a id='toc0_'></a>    
- [Fundamentals of Data Manipulation with Python](#toc1_)    
  - [Overview of Python Programming](#toc1_1_)    
    - [Functions](#toc1_1_1_)    
    - [Types and Sequences](#toc1_1_2_)    
    - [More on Strings](#toc1_1_3_)    
    - [Reading and Writing CSV files](#toc1_1_4_)    
    - [Dates and Times](#toc1_1_5_)    
    - [Objects and map()](#toc1_1_6_)    
    - [Lambda and List Comprehensions](#toc1_1_7_)    
  - [Numerical Python Library (NumPy)](#toc1_2_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# <a id='toc1_'></a>[Fundamentals of Data Manipulation with Python](#toc0_)

## <a id='toc1_1_'></a>[Overview of Python Programming](#toc0_)

### <a id='toc1_1_1_'></a>[Functions](#toc0_)

In [1]:
x = 1
y = 1
x + y

2

In [2]:
x

1

In [3]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

In [4]:
def add_numbers(x, y, z=None):
    if (z == None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, 3))
print(add_numbers(1, 2))

6
3


In [5]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z

print(add_numbers(1, 2, flag=True))

Flag is true!
3


In [6]:
a = add_numbers
a(1, 2)

3


### <a id='toc1_1_2_'></a>[Types and Sequences](#toc0_)

In [7]:
type(None)

NoneType

In [8]:
type('Hello')

str

In [9]:
type(1)

int

In [10]:
type(1.0)

float

In [11]:
type(add_numbers)

function

In [12]:
x=(1, 'a', 2, 'b')
type(x)

tuple

In [13]:
x=[1, 'a', 2, 'b']
type(x)

list

In [14]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [15]:
for item in x:
    print(item)

1
a
2
b
3.3


In [16]:
i = 0
while (i != len(x)):
    print(x[i])
    i += 1

1
a
2
b
3.3


In [17]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [18]:
[1] * 3

[1, 1, 1]

In [19]:
1 in [1, 2, 3]

True

In [20]:
x = 'This is a string!'

print(x[0])
print(x[0:1])
print(x[0:2])

T
T
Th


In [21]:
x[-1]

'!'

In [22]:
x[:3]

'Thi'

In [23]:
x[3:]

's is a string!'

In [24]:
firstname = 'Aivann Paul'
lastname = 'Butial'

print(firstname + ' ' + lastname)
print(firstname * 3)
print('Aivann' in firstname)

Aivann Paul Butial
Aivann PaulAivann PaulAivann Paul
True


In [25]:
name = 'Aivann Paul Butial'
firstname = name.split(' ')[0]
lastname = name.split(' ')[-1]

print(firstname)
print(lastname)

Aivann
Butial


In [26]:
x = {
    'Aivann Butial': 'aivannpaulbutial@proton.me',
    'John Doe': 'johndoe@gmail.com'
}

x['Aivann Butial']

'aivannpaulbutial@proton.me'

In [27]:
x['Juan Tomas'] = None
x['Juan Tomas']

In [28]:
for name in x:
    print(x[name])

aivannpaulbutial@proton.me
johndoe@gmail.com
None


In [29]:
for email in x.values():
    print(email)

aivannpaulbutial@proton.me
johndoe@gmail.com
None


In [30]:
for name in x.keys():
    print(name)

Aivann Butial
John Doe
Juan Tomas


In [31]:
for name, email in x.items():
    print(name + ':', email)

Aivann Butial: aivannpaulbutial@proton.me
John Doe: johndoe@gmail.com
Juan Tomas: None


In [32]:
x = ('Aivann', 'Butial', 'aivannpaulbutial@proton.me')
fname, lname, email = x

In [33]:
fname, lname, email

('Aivann', 'Butial', 'aivannpaulbutial@proton.me')

### <a id='toc1_1_3_'></a>[More on Strings](#toc0_)

In [34]:
print('Aivann' + str(2))

Aivann2


In [35]:
sales_record = {
    'price': 3.24,
    'num_items': 4,
    'person': 'Chris'
}

sales_statement = '{} bought {} items at a price of {} each for a total of {}'
print(
    sales_statement.format(
        sales_record['person'],
        sales_record['num_items'],
        sales_record['price'],
        sales_record['num_items'] * sales_record['price']
    )
)

Chris bought 4 items at a price of 3.24 each for a total of 12.96


### <a id='toc1_1_4_'></a>[Reading and Writing CSV files](#toc0_)

In [1]:
import csv

%precision 2

with open('datasets/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3]

[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

In [2]:
len(mpg)

234

In [3]:
mpg[0].keys()

dict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [4]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [5]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

In [6]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [7]:
CtyMpgByCyl = []

for c in cylinders:
    summpg = 0
    cyltypecount = 0
    for d in mpg:
        if d['cyl'] == c:
            summpg += float(d['cty'])
            cyltypecount += 1
    CtyMpgByCyl.append((c, summpg / cyltypecount))
    
CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [8]:
vehicleclass = set(d['class'] for d in mpg)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [9]:
HwyMpgByClass = []
for t in vehicleclass:
    summpg = 0
    vclasscount = 0
    for d in mpg:
        if d['class'] == t:
            summpg += float(d['hwy'])
            vclasscount += 1
            
    HwyMpgByClass.append((t, summpg / vclasscount))
    
HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

### <a id='toc1_1_5_'></a>[Dates and Times](#toc0_)

In [10]:
import datetime as dt
import time as tm

tm.time()

1784793090.64

In [11]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2026, 7, 23, 15, 52, 3, 955039)

In [12]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2026, 7, 23, 15, 52, 3)

In [13]:
delta = dt.timedelta(days = 100)
delta

datetime.timedelta(days=100)

In [15]:
today = dt.date.today()
today

datetime.date(2026, 7, 23)

In [16]:
today - delta

datetime.date(2026, 4, 14)

In [17]:
today > today - delta

True

### <a id='toc1_1_6_'></a>[Objects and map()](#toc0_)

In [18]:
class Person:
    department = 'School of Information'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [21]:
person = Person()
person.set_name('Aivann')
person.set_location('Cavite')

print(person.name, person.location)

Aivann Cavite


In [ ]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 =  [9.00, 11.10, 12.34, 2.01]

cheapest = map(min, store1, store2)
cheapest # lazy evaluation

In [24]:
for val in cheapest:
    print(val)

9.0
11.0
12.34
2.01


### <a id='toc1_1_7_'></a>[Lambda and List Comprehensions](#toc0_)

In [26]:
my_function = lambda a, b, c: a + b

In [27]:
my_function(1, 2, 3)

3

In [29]:
evens = []
for num in range(0, 10):
    if num % 2 == 0:
        evens.append(num)
evens

[0, 2, 4, 6, 8]

In [31]:
evens = [num for num in range(0, 10) if num % 2 == 0]
evens

[0, 2, 4, 6, 8]

## <a id='toc1_2_'></a>[Numerical Python Library (NumPy)](#toc0_)

### Creating Array

In [32]:
import numpy as np
import math

In [34]:
a = np.array([1, 2, 3])

print(a)
print(a.ndim)

[1 2 3]
1


In [38]:
b = np.array([[1,2,3], [4,5,6]])

print(b)
print(b.ndim)
print(b.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [39]:
a.dtype

dtype('int64')

In [40]:
c = np.array([2.2, 5, 1.1])
c.dtype.name

'float64'

In [41]:
zeros = np.zeros((2,3))
print(zeros)

ones = np.ones((2,3))
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [42]:
np.random.rand(2,3)

array([[0.457866  , 0.24860496, 0.29894505],
       [0.01483059, 0.54592872, 0.16302848]])

In [44]:
f = np.arange(10, 50, 2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [45]:
np.linspace(0, 2, 15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])